version: '3.1'

services:

  mysqldb:
    image: clarius.jfrog.io/clari-docker-v0-virtual/mysql
    restart: always
    ports:
    - "33307:3306"
    volumes:
    - ".docker/mysqldb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root